[versions]
kotlin = "2.2.10"
alchemist = "42.3.6"
collektive = "27.1.0"

[libraries]
alchemist = { module = "it.unibo.alchemist:alchemist", version.ref = "alchemist" }
alchemist-swingui = { module = "it.unibo.alchemist:alchemist-swingui", version.ref = "alchemist" }
alchemist-ui-tooling = { module = "it.unibo.alchemist:alchemist-ui-tooling", version.ref = "alchemist" }
alchemist-euclidean-geometry = { module = "it.unibo.alchemist:alchemist-euclidean-geometry", version.ref = "alchemist" }
collektive = { module = "it.unibo.collektive:collektive-dsl", version.ref = "collektive" }
collektive-incarnation = { module = "it.unibo.collektive:alchemist-incarnation-collektive", version.ref = "collektive" }
collektive-stdlib = { module = "it.unibo.collektive:collektive-stdlib", version.ref = "collektive" }

[bundles]
alchemist = [
    "alchemist",
    "alchemist-euclidean-geometry",
    "alchemist-swingui",
    "alchemist-ui-tooling"
]
collektive = ["collektive", "collektive-incarnation", "collektive-stdlib"]

[plugins]
collektive = { id = "it.unibo.collektive.collektive-plugin", version.ref = "collektive" }
gitSemVer = { id = "org.danilopianini.git-sensitive-semantic-versioning", version = "7.0.4" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
taskTree = { id = "com.dorongold.task-tree", version = "4.0.1" }